### PR TITLE
Fixed incompatibility with stock logger when using blocks

### PR DESCRIPTION
**Pull request by chancancode**
Specifically, `logger.debug('progname') { "A message inside a block" }` behaves differently in SyslogLogger and stock logger. In stock logger, "progname" is taken as the progname, and the block will be eval'ed and the result will be used as the log message. In SyslogLogger, "progname" is taken as the message and the block is never evaluated.

### CODE REVIEW

**Comment by chancancode** [comment]
@tenderlove I noticed that you forked this repo and is prep-ing for a v2.0. However the master branch of this repository seems corrupted... for some reason a bunch of commits were overwritten and lost in the master repo. (See above.) Can you look into this? You might want to pull/rebase from the master branch in my fork.

/cc @drbrain @zenspider

**Comment by tenderlove** [comment]
Sorry, this repo isn't canonical anymore (but I can't delete it due to the seattlerb p4 sync).  Can you send the PR to sparklemotion/sysloglogger ?  It is considered canonical now.

**Comment by zenspider** [comment]
On Dec 4, 2012, at 11:39 , Aaron Patterson notifications@github.com wrote:

> Sorry, this repo isn't canonical anymore (but I can't delete it due to the seattlerb p4 sync). Can you send the PR to sparklemotion/sysloglogger ? It is considered canonical now.

I can nuke it.

**Comment by zenspider** [comment]
Sync is turned off. Since there are open issues, I'm not going to delete the project. Please migrate the issues and delete.

**Comment by tenderlove** [comment]
OK. Thanks @zenspider

**Comment by chancancode** [comment]
Moved this to sparklemotion/sysloglogger#2 and sparklemotion/sysloglogger#3. Closing this ticket here.

**Pull request closed without merging**
